image: node:20

definitions:
  steps:
    - step: &build-and-push-service
       name: Build & Push Service
       services:
        - docker
       caches:
        - docker
       script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        # Definimos las variables completas de la imagen usando las del entorno de Bitbucket
        - IMAGE_COMMIT="$DOCKER_USER/$SERVICE_NAME:$BITBUCKET_COMMIT"
        - IMAGE_LATEST="$DOCKER_USER/$SERVICE_NAME:latest"

        - echo "Building and pushing service $SERVICE_NAME..."
        # Build de la imagen con el tag del commit
        - docker build -t "$IMAGE_COMMIT" "$DOCKERFILE_PATH"

        # Creamos el tag latest apuntando al mismo build
        - docker tag "$IMAGE_COMMIT" "$IMAGE_LATEST"

        # Push de ambos tags a Docker Hub
        - docker push "$IMAGE_COMMIT"
        - docker push "$IMAGE_LATEST"

    - step: &build
        name: Build (required)
        caches:
          - node
        script:
          - npm ci
          - npm run build
    - step: &test
        name: Tests — Unit + Integration (required)
        caches:
          - node
        script:
          - npm ci
          - npm install --prefix services/inscriptions-svc
          - npm install --prefix services/tournaments-svc
          - npm run test:ci

pipelines:
#  pull-requests:
#    '**':
#      - step: *build
#      - step: *test

  branches:
    main:
      - step: *build
      - step: *test
      - parallel:
          - step:
              <<: *build-and-push-service
              name: Deploy — Frontend
              env:
                SERVICE_NAME: "liga360-frontend"
                DOCKERFILE_PATH: "-f Dockerfile.frontend ."
          - step:
              <<: *build-and-push-service
              name: Deploy — Auth Svc
              env:
                SERVICE_NAME: "liga360-auth-svc"
                DOCKERFILE_PATH: "./services/auth-svc"
          - step:
              <<: *build-and-push-service
              name: Deploy — Gateway
              env:
                SERVICE_NAME: "liga360-gateway"
                DOCKERFILE_PATH: "./services/gateway"
          - step:
              <<: *build-and-push-service
              name: Deploy — Inscriptions Svc
              env:
                SERVICE_NAME: "liga360-inscriptions-svc"
                DOCKERFILE_PATH: "./services/inscriptions-svc"
          - step:
              <<: *build-and-push-service
              name: Deploy — Teams Svc
              env:
                SERVICE_NAME: "liga360-teams-svc"
                DOCKERFILE_PATH: "./services/teams-svc"
          - step:
              <<: *build-and-push-service
              name: Deploy — Tournaments Svc
              env:
                SERVICE_NAME: "liga360-tournaments-svc"
                DOCKERFILE_PATH: "./services/tournaments-svc"