apiVersion: batch/v1
kind: Job
metadata:
  name: inscriptions-svc-migration
  labels:
    app: inscriptions-svc-migration
    app.kubernetes.io/part-of: liga360
  annotations:
    # Ejecutar la migración antes de desplegar los nuevos pods
    argocd.argoproj.io/hook: PreSync
    # Eliminar el pod efímero de migración tras el éxito
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: inscriptions-svc-migration
    spec:
      containers:
        - name: migrate
          image: liga360/inscriptions-svc:latest # Misma imagen que tu Deployment
          imagePullPolicy: IfNotPresent
          command: ["npm", "run", "migrate"]     # Comando para node-pg-migrate
          envFrom:
            - configMapRef:
                name: liga360-config
            - secretRef:
                name: liga360-secrets
          env:
            - name: DATABASE_URL
              value: $(POSTGRES_URL)
      restartPolicy: Never