apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: liga360-secrets-es
  # The namespace is inherited from kustomization.yaml (liga360)
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: liga360-secrets # Name of the K8s Secret that will be created
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: liga360-secrets
        property: JWT_SECRET
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: liga360-secrets
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_URL
      remoteRef:
        key: liga360-secrets
        property: POSTGRES_URL
    - secretKey: NEO4J_PASSWORD
      remoteRef:
        key: liga360-secrets
        property: NEO4J_PASSWORD
    - secretKey: NEO4J_AUTH
      remoteRef:
        key: liga360-secrets
        property: NEO4J_AUTH

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: liga360-app-sa
  # Los deployments de tu app (auth-svc, etc) pueden configurarse con:
  # serviceAccountName: liga360-app-sa
