apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    app.kubernetes.io/part-of: liga360
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: gateway
