apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: liga360/frontend
    newName: bcanevaro/liga360-frontend
    newTag: latest
  - name: liga360/gateway
    newName: bcanevaro/liga360-gateway
    newTag: latest
  - name: liga360/auth-svc
    newName: bcanevaro/liga360-auth-svc
    newTag: latest
  - name: liga360/teams-svc
    newName: bcanevaro/liga360-teams-svc
    newTag: latest
  - name: liga360/tournaments-svc
    newName: bcanevaro/liga360-tournaments-svc
    newTag: latest
  - name: liga360/inscriptions-svc
    newName: bcanevaro/liga360-inscriptions-svc
    newTag: latest
