apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: liga360/migrator
    newName: bcanevaro/liga360-migrator
    newTag: 82d375fbb84c60a745c5260df4a77f47f97caed8
  - name: liga360/frontend
    newName: bcanevaro/liga360-frontend
    newTag: 82d375fbb84c60a745c5260df4a77f47f97caed8
  - name: liga360/gateway
    newName: bcanevaro/liga360-gateway
    newTag: 82d375fbb84c60a745c5260df4a77f47f97caed8
  - name: liga360/auth-svc
    newName: bcanevaro/liga360-auth-svc
    newTag: 82d375fbb84c60a745c5260df4a77f47f97caed8
  - name: liga360/teams-svc
    newName: bcanevaro/liga360-teams-svc
    newTag: 82d375fbb84c60a745c5260df4a77f47f97caed8
  - name: liga360/tournaments-svc
    newName: bcanevaro/liga360-tournaments-svc
    newTag: 82d375fbb84c60a745c5260df4a77f47f97caed8
  - name: liga360/inscriptions-svc
    newName: bcanevaro/liga360-inscriptions-svc
    newTag: 82d375fbb84c60a745c5260df4a77f47f97caed8

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{name: credenciales-dockerhub}]
