apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liga360

resources:
  - ../../base
  - ingress.yaml

images:
  - name: liga360-migrator
    newName: bcanevaro/liga360-migrator
    newTag: 04d1364dd398412118caa81b47c3395804451a5d
  - name: liga360-frontend
    newName: bcanevaro/liga360-frontend
    newTag: d1940e0bd92dfade94b705fc002168a01217f77c
  - name: liga360-gateway
    newName: bcanevaro/liga360-gateway
    newTag: 871510f6c005ce23ba65a6ac9243d1d137c0af06
  - name: liga360-auth-svc
    newName: bcanevaro/liga360-auth-svc
    newTag: 871510f6c005ce23ba65a6ac9243d1d137c0af06
  - name: liga360-teams-svc
    newName: bcanevaro/liga360-teams-svc
    newTag: 0a1f40bf25de81ed28c27da3c4fd9b5d7baafd9f
  - name: liga360-tournaments-svc
    newName: bcanevaro/liga360-tournaments-svc
    newTag: 0a1f40bf25de81ed28c27da3c4fd9b5d7baafd9f
  - name: liga360-inscriptions-svc
    newName: bcanevaro/liga360-inscriptions-svc
    newTag: 0a1f40bf25de81ed28c27da3c4fd9b5d7baafd9f
  - name: liga360-matchevents-svc
    newName: bcanevaro/liga360-matchevents-svc
    newTag: 0a1f40bf25de81ed28c27da3c4fd9b5d7baafd9f
